name: Release

on:
  push:
    tags:
      - "v*"
      - "*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/common/lint.yml
  test:
    name: Test
    uses: ./.github/workflows/common/test.yml
  build:
    name: Build
    uses: ./.github/workflows/common/build.yml
  publish:
    name: Publish
    uses: ./.github/workflows/common/publish.yml
